# Generated by Django 5.1.5 on 2025-02-26 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers_app', '0007_product_discount_percent_product_is_on_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
