# Generated by Django 5.1.5 on 2025-02-27 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers_app', '0011_alter_order_cart_alter_order_ord_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash on Delivery'), ('KHALTI', 'Khalti Payment')], max_length=10),
        ),
    ]
