# Generated by Django 5.1.5 on 2025-02-27 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers_app', '0013_alter_order_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_names',
            field=models.JSONField(default=list),
        ),
    ]
