# Generated by Django 5.1.5 on 2025-02-28 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers_app', '0014_order_product_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
