# Generated by Django 5.2.2 on 2025-06-16 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sneakers_app', '0017_order_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
